<div class="row">
    <div class="col-8 mb-3">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Procurar cogumelos" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-outline-primary" type="button">
                Pesquisar...
            </button>
        </div>
    </div>
    <div class="col-4">
        <a href="<?= route('mushrooms.new') ?>" class="btn btn-outline-primary">
            <i class="fe fe-plus"></i>
            Registrar Cogumelo
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th></th>
    </thead>
    <tbody>
        <?php foreach ($mushrooms as $mushroom) : ?>
            <tr>
                <td><a href="<?= route('mushrooms.show', ['id' => $mushroom->id]) ?>">#<?= $mushroom->id ?></a></td>
                <td><?= $mushroom->scientific_name ?></td>
                <td>
                    <div class="d-flex justify-content-end align-items-center gap-2">
                        <a href="<?= route('mushrooms.edit', ['id' => $mushroom->id]) ?>" class="btn btn-link p-0">
                            <i class="bi bi-pencil-square fs-5"></i>
                        </a>
                        <form action="<?= route('mushrooms.destroy', ['id' => $mushroom->id]) ?>" method="POST" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-link p-0">
                                <i class="bi bi-trash text-danger fs-5"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php $paginator->renderPagesNavigation(); ?>