<head>
    <script src="https://unpkg.com/feather-icons"></script>
    <style>
        a.btn i[data-feather] {
            width: 1em;
            height: 1em;
            vertical-align: middle;
            stroke-width: 2;
            margin-right: 0.25em;
        }
    </style>
</head>

<form action="<?= route('mushrooms.create') ?>" method="POST" class="<?= $mushroom->hasErrors() ? 'was-validated' : '' ?>" novalidate>
    <div class="mb-3">
        <label for="scientific_name" class="form-label">Nome Científico</label>
        <input type="text" value="<?= $mushroom->scientific_name ?>" name="mushroom[scientific_name]" class="form-control" id="scientific_name" required>
        <div class="invalid-feedback"><?= $mushroom->errors('scientific_name') ?? '' ?></div>
    </div>

    <div class="mb-3">
        <label for="image_url" class="form-label">URL da Imagem</label>
        <input type="url" value="<?= $mushroom->image_url ?>" name="mushroom[image_url]" class="form-control" id="image_url" required>
        <div class="invalid-feedback"><?= $mushroom->errors('image_url') ?? '' ?></div>
    </div>

    <div class="mb-3">
        <label for="hint" class="form-label">Dica</label>
        <input type="text" value="<?= $mushroom->hint ?>" name="mushroom[hint]" class="form-control" id="hint" required>
        <div class="invalid-feedback"><?= $mushroom->errors('hint') ?? '' ?></div>
    </div>

    <div class="mb-3">
        <label for="description" class="form-label">Descrição</label>
        <textarea name="mushroom[description]" class="form-control" id="description" required><?= $mushroom->description ?></textarea>
        <div class="invalid-feedback"><?= $mushroom->errors('description') ?? '' ?></div>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>
    <a href="/mushrooms" class="btn btn-outline-primary">
        <i data-feather="arrow-left"></i> Voltar
    </a>

    <script>
        feather.replace();
    </script>
</form>