<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="assets/images/defaults/favicon-32x32.png" type="image/png">
    <title>Mushroom ID</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>


<body>
    <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= route('root') ?>">🍄 Mushroom ID</a>

            <?php if ($this->current_user): ?>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" href="<?= route('quizzes.index') ?>">Quizzes</a>
                        </li>

                        <?php if ($this->current_user->is_admin): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= route('mushrooms.index') ?>">Cogumelos</a>
                            </li>
                        <?php endif; ?>
                    </ul>

                    <div class="nav-item dropdown ms-auto">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            <?= $this->current_user->email ?>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="<?= route('users.logout') ?>">Sair</a></li>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </nav>

    <main class="container-fluid">
        <div class="row">
            <section id="main-content" class="col">

                <?php require '_flash_message.phtml'; ?>

                <header class="mb-3">
                    <h1>
                        <?= $title ?>
                    </h1>
                </header>

                <?php require $view ?>

            </section>
        </div>
    </main>
</body>

</html>